import type { Metadata } from "next";
import "./globals.css";
import FinalThemeProvider from "./components/theme-provider";
import DisplayMode from "./components/display-mode";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <FinalThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
          <DisplayMode className="absolute top-20 right-20 z-10" />
          {children}
        </FinalThemeProvider>
      </body>
    </html>
  );
}
